from __future__ import annotations

import pytest
from hypothesis import given
from hypothesis import strategies as st

from neon_mcp.neon.filenames import parse_neon_filename

TS = "20250128T000000Z"


@pytest.mark.parametrize(
    ("name", "kind", "table", "hor", "ver", "tmi", "month", "package", "ext"),
    [
        (
            f"NEON.D16.ABBY.DP1.00001.001.000.010.030.2DWSD_30min.2023-01.basic.{TS}.csv",
            "data",
            "2DWSD_30min",
            "000",
            "010",
            "030",
            "2023-01",
            "basic",
            "csv",
        ),
        (
            f"NEON.D16.ABBY.DP1.00001.001.000.010.002.2DWSD_2min.2023-01.basic.{TS}.csv",
            "data",
            "2DWSD_2min",
            "000",
            "010",
            "002",
            "2023-01",
            "basic",
            "csv",
        ),
        (
            f"NEON.D01.HARV.DP1.00098.001.000.060.001.RH_1min.2023-06.expanded.{TS}.csv",
            "data",
            "RH_1min",
            "000",
            "060",
            "001",
            "2023-06",
            "expanded",
            "csv",
        ),
        (
            f"NEON.D01.HARV.DP1.00041.001.003.502.030.ST_30_minute.2020-07.basic.{TS}.csv",
            "data",
            "ST_30_minute",
            "003",
            "502",
            "030",
            "2020-07",
            "basic",
            "csv",
        ),
        (
            f"NEON.D01.HARV.DP1.10003.001.brd_countdata.2023-06.basic.{TS}.csv",
            "data",
            "brd_countdata",
            None,
            None,
            None,
            "2023-06",
            "basic",
            "csv",
        ),
        (
            f"NEON.D01.HARV.DP1.10003.001.brd_perpoint.2023-06.basic.{TS}.csv",
            "data",
            "brd_perpoint",
            None,
            None,
            None,
            "2023-06",
            "basic",
            "csv",
        ),
        (
            f"NEON.D01.HARV.DP1.10003.001.brd_references.2023-06.basic.{TS}.csv",
            "data",
            "brd_references",
            None,
            None,
            None,
            "2023-06",
            "basic",
            "csv",
        ),
        (
            f"NEON.D14.SRER.DP1.10098.001.vst_apparentindividual.2022-03.basic.{TS}.csv",
            "data",
            "vst_apparentindividual",
            None,
            None,
            None,
            "2022-03",
            "basic",
            "csv",
        ),
        (
            f"NEON.D16.ABBY.DP1.00001.001.readme.{TS}.txt",
            "readme",
            None,
            None,
            None,
            None,
            None,
            None,
            "txt",
        ),
        (
            f"NEON.D01.HARV.DP1.10003.001.readme.{TS}.txt",
            "readme",
            None,
            None,
            None,
            None,
            None,
            None,
            "txt",
        ),
        (
            f"NEON.D16.ABBY.DP1.00001.001.variables.{TS}.csv",
            "variables",
            None,
            None,
            None,
            None,
            None,
            None,
            "csv",
        ),
        (
            f"NEON.D01.HARV.DP1.10003.001.variables_10003.{TS}.csv",
            "variables",
            None,
            None,
            None,
            None,
            None,
            None,
            "csv",
        ),
        (
            f"NEON.D16.ABBY.DP1.00001.001.sensor_positions.{TS}.csv",
            "sensor_positions",
            None,
            None,
            None,
            None,
            None,
            None,
            "csv",
        ),
        (
            f"NEON.D01.HARV.DP1.10003.001.EML.20230601-20230630.{TS}.xml",
            "eml",
            None,
            None,
            None,
            None,
            None,
            None,
            "xml",
        ),
        (
            f"NEON.D16.ABBY.DP1.00001.001.EML.20230101-20230131.{TS}.xml",
            "eml",
            None,
            None,
            None,
            None,
            None,
            None,
            "xml",
        ),
        (
            f"NEON.D01.HARV.DP1.00098.001.science_review_flags_RH.2023-06.expanded.{TS}.csv",
            "science_review_flags",
            "science_review_flags_RH",
            None,
            None,
            None,
            "2023-06",
            "expanded",
            "csv",
        ),
        (
            f"NEON.D01.HARV.DP1.10003.001.categoricalCodes_10003.{TS}.csv",
            "categorical_codes",
            "categoricalCodes_10003",
            None,
            None,
            None,
            None,
            None,
            "csv",
        ),
        (
            f"NEON.D01.HARV.DP1.10003.001.validation_10003.{TS}.csv",
            "validation",
            "validation_10003",
            None,
            None,
            None,
            None,
            None,
            "csv",
        ),
        (
            f"NEON.D16.ABBY.DP1.00001.001.2023-01.basic.{TS}.zip",
            "package",
            None,
            None,
            None,
            None,
            "2023-01",
            "basic",
            "zip",
        ),
        (
            "NEON_D16_ABBY_DP3_552000_5071000_CHM.tif",
            "other",
            None,
            None,
            None,
            None,
            None,
            None,
            "tif",
        ),
        ("NEON_reaeration_BLUE_2016.zip", "package", None, None, None, None, None, None, "zip"),
        (
            "NEON.PROTOTYPE.DATASET.EML.07dccab1.xml",
            "other",
            None,
            None,
            None,
            None,
            None,
            None,
            "xml",
        ),
        ("", "other", None, None, None, None, None, None, None),
        ("README", "other", None, None, None, None, None, None, None),
        (
            f"path/to/NEON.D16.ABBY.DP1.00001.001.readme.{TS}.txt",
            "readme",
            None,
            None,
            None,
            None,
            None,
            None,
            "txt",
        ),
    ],
)
def test_grammar(
    name: str,
    kind: str,
    table: str | None,
    hor: str | None,
    ver: str | None,
    tmi: str | None,
    month: str | None,
    package: str | None,
    ext: str | None,
) -> None:
    p = parse_neon_filename(name)
    assert (p.kind, p.table, p.hor, p.ver, p.tmi, p.month, p.package, p.ext) == (
        kind,
        table,
        hor,
        ver,
        tmi,
        month,
        package,
        ext,
    )


def test_prefix_fields() -> None:
    p = parse_neon_filename(
        f"NEON.D16.ABBY.DP1.00001.001.000.010.030.2DWSD_30min.2023-01.basic.{TS}.csv"
    )
    assert (p.domain, p.site, p.product_code, p.timestamp) == ("D16", "ABBY", "DP1.00001.001", TS)


@given(st.text(max_size=200))
def test_never_raises(name: str) -> None:
    assert parse_neon_filename(name).kind
